### ISSUE TITLE
API 应该怎么填 

### ISSUE THREAD

**Issue by LwdAmazing** [tediorelee/koishi-plugin-javbus#1]

**Comment by LwdAmazing** [comment]
http://10.10.10.4:8922/api 或者这样 http://10.10.10.4:8922/  但是这俩返回都是
发生错误!请检查发送的番号是否正确;  AxiosError: Request failed with status code 404

**Comment by tediorelee** [comment]
> http://10.10.10.4:8922/api 或者这样 http://10.10.10.4:8922/ 但是这俩返回都是 发生错误!请检查发送的番号是否正确; AxiosError: Request failed with status code 404

填写ip和端口就足够了 eg: http://ip:port
